name: Semantic Version Release CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install and use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn project:semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}